from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Any


RUNBOOK_FIELDS = [
    "run_order",
    "action_priority",
    "pdb_id",
    "method",
    "action_tier",
    "current_status",
    "expected_return_path",
    "portable_command",
    "notes",
]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Convert the CD38 external benchmark action plan into a portable next-run runbook "
            "for the machine that will run P2Rank/fpocket."
        )
    )
    parser.add_argument(
        "--action_plan_csv",
        default="benchmarks/cd38/action_plan/cd38_external_benchmark_action_plan.csv",
        help="Action plan CSV generated by build_cd38_external_benchmark_action_plan.py.",
    )
    parser.add_argument(
        "--package_dir",
        default="benchmarks/cd38/external_tool_inputs",
        help="External-tool package directory that contains PDB inputs and templates.",
    )
    parser.add_argument(
        "--include_package_reproducibility",
        action="store_true",
        help="Also include package-only reproducibility rows, not only benchmark completion gaps.",
    )
    parser.add_argument(
        "--include_ready",
        action="store_true",
        help="Include rows that are already detected as ready.",
    )
    parser.add_argument(
        "--out_prefix",
        default="cd38_external_tool_next_run",
        help="Output filename prefix written under package_dir.",
    )
    return parser


def _repo_root() -> Path:
    return Path(__file__).resolve().parent


def _resolve(path: str | Path, repo_root: Path) -> Path:
    target = Path(path).expanduser()
    if not target.is_absolute():
        target = repo_root / target
    return target.resolve()


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=True, indent=2), encoding="utf-8")


def _truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "yes", "y", "on"}


def _safe_int(value: Any, default: int = 99) -> int:
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _norm_pdb(value: Any) -> str:
    return str(value or "").strip().upper()


def _norm_method(value: Any) -> str:
    return str(value or "").strip().lower()


def _method_ready(value: Any) -> bool:
    return str(value or "").strip().lower().startswith("ready")


def _portable_command(row: dict[str, Any]) -> str:
    pdb_id = _norm_pdb(row.get("pdb_id"))
    method = _norm_method(row.get("method"))
    if method == "p2rank":
        return f'prank predict -f "pdbs/{pdb_id}.pdb" -o "p2rank_outputs/{pdb_id}"'
    if method == "fpocket":
        return f'cd "fpocket_runs/{pdb_id}" && fpocket -f "{pdb_id}.pdb"'
    return ""


def _select_rows(
    rows: list[dict[str, str]],
    *,
    include_package_reproducibility: bool,
    include_ready: bool,
) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for row in rows:
        method = _norm_method(row.get("method"))
        if method not in {"p2rank", "fpocket"}:
            continue
        action_tier = str(row.get("action_tier") or "").strip()
        benchmark_gap = _truthy(row.get("benchmark_gap")) or action_tier == "benchmark_completion"
        if not benchmark_gap and not include_package_reproducibility:
            continue
        if _method_ready(row.get("current_status")) and not include_ready:
            continue
        selected.append(dict(row))
    selected.sort(
        key=lambda row: (
            _safe_int(row.get("action_priority")),
            0 if str(row.get("action_tier") or "") == "benchmark_completion" else 1,
            _norm_pdb(row.get("pdb_id")),
            _norm_method(row.get("method")),
        )
    )
    return selected


def _build_runbook_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    runbook_rows: list[dict[str, Any]] = []
    for index, row in enumerate(rows, start=1):
        runbook_rows.append(
            {
                "run_order": index,
                "action_priority": row.get("action_priority", ""),
                "pdb_id": _norm_pdb(row.get("pdb_id")),
                "method": _norm_method(row.get("method")),
                "action_tier": row.get("action_tier", ""),
                "current_status": row.get("current_status", ""),
                "expected_return_path": row.get("expected_return_path", ""),
                "portable_command": _portable_command(row),
                "notes": row.get("notes", ""),
            }
        )
    return runbook_rows


def _build_ps1(rows: list[dict[str, Any]]) -> str:
    need_p2rank = any(row.get("method") == "p2rank" for row in rows)
    need_fpocket = any(row.get("method") == "fpocket" for row in rows)
    lines = [
        "# Generated by build_cd38_external_tool_runbook.py",
        "# Run only the CD38 external-tool actions that are still missing from the action plan.",
        "$ErrorActionPreference = 'Stop'",
        "$PackageRoot = Split-Path -Parent $MyInvocation.MyCommand.Path",
        "",
        "function Require-Command {",
        "    param([string]$Name)",
        "    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {",
        "        throw \"Required command not found in PATH: $Name\"",
        "    }",
        "}",
        "",
        "function Require-File {",
        "    param([string]$Path)",
        "    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {",
        "        throw \"Required input file not found: $Path\"",
        "    }",
        "}",
        "",
    ]
    if need_p2rank:
        lines.append("Require-Command 'prank'")
    if need_fpocket:
        lines.append("Require-Command 'fpocket'")
    if need_p2rank or need_fpocket:
        lines.append("")
    lines.append(f"Write-Host \"Running {len(rows)} CD38 external-tool action(s).\"")
    lines.append("")
    if not rows:
        lines.extend(
            [
                "Write-Host 'No missing benchmark actions were selected.'",
                "exit 0",
                "",
            ]
        )
        return "\n".join(lines)

    for row in rows:
        order = row.get("run_order")
        pdb_id = row.get("pdb_id")
        method = row.get("method")
        lines.append(f"Write-Host \"[{order}/{len(rows)}] {pdb_id} {method}\"")
        if method == "p2rank":
            lines.extend(
                [
                    f"$PdbPath = Join-Path $PackageRoot \"pdbs\\{pdb_id}.pdb\"",
                    f"$OutDir = Join-Path $PackageRoot \"p2rank_outputs\\{pdb_id}\"",
                    "$null = New-Item -ItemType Directory -Force -Path $OutDir",
                    "Require-File $PdbPath",
                    "prank predict -f $PdbPath -o $OutDir",
                    "",
                ]
            )
        elif method == "fpocket":
            lines.extend(
                [
                    f"$RunDir = Join-Path $PackageRoot \"fpocket_runs\\{pdb_id}\"",
                    f"$RunPdb = Join-Path $RunDir \"{pdb_id}.pdb\"",
                    "Require-File $RunPdb",
                    "Push-Location $RunDir",
                    "try {",
                    f"    fpocket -f \"{pdb_id}.pdb\"",
                    "} finally {",
                    "    Pop-Location",
                    "}",
                    "",
                ]
            )
    lines.extend(
        [
            "Write-Host 'External-tool actions finished.'",
            "Write-Host 'Return the whole package folder or zip it, then import/finalize in the original ML project.'",
            "",
        ]
    )
    return "\n".join(lines)


def _build_sh(rows: list[dict[str, Any]]) -> str:
    need_p2rank = any(row.get("method") == "p2rank" for row in rows)
    need_fpocket = any(row.get("method") == "fpocket" for row in rows)
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by build_cd38_external_tool_runbook.py",
        "# Run only the CD38 external-tool actions that are still missing from the action plan.",
        "set -euo pipefail",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        "",
        "require_command() {",
        "  if ! command -v \"$1\" >/dev/null 2>&1; then",
        "    echo \"Required command not found in PATH: $1\" >&2",
        "    exit 2",
        "  fi",
        "}",
        "",
        "require_file() {",
        "  if [[ ! -f \"$1\" ]]; then",
        "    echo \"Required input file not found: $1\" >&2",
        "    exit 3",
        "  fi",
        "}",
        "",
    ]
    if need_p2rank:
        lines.append('require_command "prank"')
    if need_fpocket:
        lines.append('require_command "fpocket"')
    if need_p2rank or need_fpocket:
        lines.append("")
    lines.append(f'echo "Running {len(rows)} CD38 external-tool action(s)."')
    lines.append("")
    if not rows:
        lines.extend(
            [
                'echo "No missing benchmark actions were selected."',
                "exit 0",
                "",
            ]
        )
        return "\n".join(lines)

    for row in rows:
        order = row.get("run_order")
        pdb_id = row.get("pdb_id")
        method = row.get("method")
        lines.append(f'echo "[{order}/{len(rows)}] {pdb_id} {method}"')
        if method == "p2rank":
            lines.extend(
                [
                    f'PDB_PATH="$SCRIPT_DIR/pdbs/{pdb_id}.pdb"',
                    f'OUT_DIR="$SCRIPT_DIR/p2rank_outputs/{pdb_id}"',
                    'mkdir -p "$OUT_DIR"',
                    'require_file "$PDB_PATH"',
                    'prank predict -f "$PDB_PATH" -o "$OUT_DIR"',
                    "",
                ]
            )
        elif method == "fpocket":
            lines.extend(
                [
                    f'RUN_DIR="$SCRIPT_DIR/fpocket_runs/{pdb_id}"',
                    f'RUN_PDB="$RUN_DIR/{pdb_id}.pdb"',
                    'require_file "$RUN_PDB"',
                    f'(cd "$RUN_DIR" && fpocket -f "{pdb_id}.pdb")',
                    "",
                ]
            )
    lines.extend(
        [
            'echo "External-tool actions finished."',
            'echo "Return the whole package folder or zip it, then import/finalize in the original ML project."',
            "",
        ]
    )
    return "\n".join(lines)


def _md(value: Any) -> str:
    return str(value or "").replace("|", "\\|")


def _display_path(summary: dict[str, Any], value: Any) -> str:
    text = str(value or "")
    package_text = str(summary.get("package_dir") or "")
    try:
        package = Path(package_text)
        path = Path(text)
        if path.is_absolute() and package.is_absolute():
            return path.relative_to(package).as_posix()
    except (OSError, ValueError):
        pass
    return text.replace("\\", "/")


def _build_report(summary: dict[str, Any], rows: list[dict[str, Any]]) -> str:
    lines = [
        "# CD38 External Tool Next Runbook",
        "",
        "This runbook is generated from the current CD38 external benchmark action plan.",
        "It is meant for the machine or WSL/Linux environment that has P2Rank and/or fpocket installed.",
        "",
        "## Summary",
        "",
        f"- Selected actions: `{summary['selected_action_count']}`",
        f"- Include package reproducibility rows: `{summary['include_package_reproducibility']}`",
        f"- Include already-ready rows: `{summary['include_ready']}`",
        f"- Need P2Rank: `{summary['need_p2rank']}`",
        f"- Need fpocket: `{summary['need_fpocket']}`",
        "",
        "## Run",
        "",
        "Windows PowerShell:",
        "",
        "```powershell",
        ".\\run_cd38_external_next_benchmark.ps1",
        "```",
        "",
        "Linux / WSL:",
        "",
        "```bash",
        "chmod +x run_cd38_external_next_benchmark.sh",
        "./run_cd38_external_next_benchmark.sh",
        "```",
        "",
        "## Return And Import",
        "",
        "After the external tools finish, return the whole completed package folder or zip it.",
        "In the original ML project, first dry-run/gate the returned folder, then finalize:",
        "",
        "```bash",
        "python finalize_cd38_external_benchmark.py --import_source returned_external_tool_inputs.zip --run_discovered --run_sensitivity",
        "```",
        "",
        "The finalize command will gate the returned package before importing. Non-PASS gate statuses are blocked by default.",
        "",
        "## Included Actions",
        "",
        "| Order | Priority | PDB | Method | Tier | Current Status | Expected Return |",
        "| ---: | ---: | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| {order} | {priority} | {pdb} | {method} | {tier} | {status} | `{expected}` |".format(
                order=_md(row.get("run_order")),
                priority=_md(row.get("action_priority")),
                pdb=_md(row.get("pdb_id")),
                method=_md(row.get("method")),
                tier=_md(row.get("action_tier")),
                status=_md(row.get("current_status")),
                expected=_md(row.get("expected_return_path")),
            )
        )
    if not rows:
        lines.append("|  |  |  |  |  |  |  |")
    lines.extend(
        [
            "",
            "## Outputs",
            "",
            f"- CSV: `{_display_path(summary, summary['outputs']['runbook_csv'])}`",
            f"- JSON: `{_display_path(summary, summary['outputs']['summary_json'])}`",
            f"- Markdown: `{_display_path(summary, summary['outputs']['report_md'])}`",
            f"- PowerShell runner: `{_display_path(summary, summary['outputs']['powershell_runner'])}`",
            f"- Bash runner: `{_display_path(summary, summary['outputs']['bash_runner'])}`",
            "",
            "## Boundary",
            "",
            "This file only describes and runs external pocket-finder tools. It does not create benchmark evidence until the returned outputs pass import gate and are finalized in the original project.",
            "",
        ]
    )
    return "\n".join(lines)


def build_cd38_external_tool_runbook(
    *,
    action_plan_csv: str | Path = "benchmarks/cd38/action_plan/cd38_external_benchmark_action_plan.csv",
    package_dir: str | Path = "benchmarks/cd38/external_tool_inputs",
    include_package_reproducibility: bool = False,
    include_ready: bool = False,
    out_prefix: str = "cd38_external_tool_next_run",
) -> dict[str, Any]:
    repo_root = _repo_root()
    action_csv = _resolve(action_plan_csv, repo_root)
    package = _resolve(package_dir, repo_root)
    package.mkdir(parents=True, exist_ok=True)

    action_rows = _read_csv(action_csv)
    selected = _select_rows(
        action_rows,
        include_package_reproducibility=include_package_reproducibility,
        include_ready=include_ready,
    )
    runbook_rows = _build_runbook_rows(selected)

    runbook_csv = package / f"{out_prefix}_plan.csv"
    summary_json = package / f"{out_prefix}_summary.json"
    report_md = package / f"{out_prefix}.md"
    ps1_path = package / "run_cd38_external_next_benchmark.ps1"
    sh_path = package / "run_cd38_external_next_benchmark.sh"

    summary: dict[str, Any] = {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "action_plan_csv": str(action_csv),
        "package_dir": str(package),
        "source_action_count": int(len(action_rows)),
        "selected_action_count": int(len(runbook_rows)),
        "include_package_reproducibility": bool(include_package_reproducibility),
        "include_ready": bool(include_ready),
        "need_p2rank": any(row.get("method") == "p2rank" for row in runbook_rows),
        "need_fpocket": any(row.get("method") == "fpocket" for row in runbook_rows),
        "outputs": {
            "runbook_csv": str(runbook_csv),
            "summary_json": str(summary_json),
            "report_md": str(report_md),
            "powershell_runner": str(ps1_path),
            "bash_runner": str(sh_path),
        },
    }

    _write_csv(runbook_csv, runbook_rows, RUNBOOK_FIELDS)
    _write_json(summary_json, summary)
    report_md.write_text(_build_report(summary, runbook_rows), encoding="utf-8")
    ps1_path.write_text(_build_ps1(runbook_rows), encoding="utf-8", newline="\n")
    sh_path.write_text(_build_sh(runbook_rows), encoding="utf-8", newline="\n")
    try:
        sh_path.chmod(0o755)
    except OSError:
        pass
    return {"summary": summary, "actions": runbook_rows}


def main() -> None:
    args = _build_parser().parse_args()
    payload = build_cd38_external_tool_runbook(
        action_plan_csv=args.action_plan_csv,
        package_dir=args.package_dir,
        include_package_reproducibility=bool(args.include_package_reproducibility),
        include_ready=bool(args.include_ready),
        out_prefix=str(args.out_prefix),
    )
    summary = payload["summary"]
    print(f"Saved: {summary['outputs']['runbook_csv']}")
    print(f"Saved: {summary['outputs']['summary_json']}")
    print(f"Saved: {summary['outputs']['report_md']}")
    print(f"Saved: {summary['outputs']['powershell_runner']}")
    print(f"Saved: {summary['outputs']['bash_runner']}")
    print(f"Selected actions: {summary['selected_action_count']}")


if __name__ == "__main__":
    main()
