from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path
from typing import Any


OUTPUT_COLUMNS = [
    "pdb_id",
    "desired_methods",
    "pdb_input_status",
    "pdb_input_path",
    "pdb_input_source",
    "p2rank_status",
    "p2rank_predictions_csv",
    "p2rank_source",
    "fpocket_status",
    "fpocket_pocket_count",
    "fpocket_pockets_dir",
    "fpocket_source",
    "notes",
]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check local environment and expected outputs for the CD38 external P2Rank/fpocket input package."
    )
    parser.add_argument(
        "--package_dir",
        default="benchmarks/cd38/external_tool_inputs",
        help="Directory generated by prepare_cd38_external_tool_inputs.py.",
    )
    parser.add_argument(
        "--manifest_csv",
        default=None,
        help="Optional external tool input manifest. Defaults to <package_dir>/cd38_external_tool_input_manifest.csv.",
    )
    parser.add_argument("--out_dir", default=None, help="Output directory. Defaults to <package_dir>/preflight.")
    parser.add_argument("--p2rank_command", default="prank", help="Executable name or path for P2Rank.")
    parser.add_argument("--fpocket_command", default="fpocket", help="Executable name or path for fpocket.")
    return parser


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return [dict(row) for row in csv.DictReader(f)]


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _split_csv(value: Any) -> list[str]:
    return [part.strip() for part in str(value or "").split(",") if part.strip()]


def _normalize_methods(value: Any) -> list[str]:
    methods: list[str] = []
    for item in _split_csv(value):
        normalized = item.lower().replace("-", "_")
        if normalized and normalized not in methods:
            methods.append(normalized)
    return methods


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError:
        return False
    return True


def _dedupe_candidates(candidates: list[tuple[Path, str]]) -> list[tuple[Path, str]]:
    seen: set[str] = set()
    deduped: list[tuple[Path, str]] = []
    for path, source in candidates:
        key = str(path).lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((path, source))
    return deduped


def _manifest_path(row: dict[str, Any], key: str, package_dir: Path) -> Path | None:
    value = str(row.get(key) or "").strip()
    if not value:
        return None
    path = Path(value)
    return path if path.is_absolute() else package_dir / path


def _candidate(path: Path | None, source: str) -> tuple[Path, str] | None:
    if path is None:
        return None
    return path, source


def _first_existing(candidates: list[tuple[Path, str]]) -> tuple[Path, str] | None:
    for path, source in _dedupe_candidates(candidates):
        if path.exists():
            return path, source
    return None


def _preferred_missing(candidates: list[tuple[Path, str]], package_dir: Path) -> tuple[str, str]:
    deduped = _dedupe_candidates(candidates)
    for path, source in deduped:
        if _is_within(path, package_dir):
            return str(path), source
    if deduped:
        path, source = deduped[0]
        return str(path), source
    return "", ""


def _portable_pdb_path(package_dir: Path, pdb_id: str) -> Path:
    return package_dir / "pdbs" / f"{pdb_id}.pdb"


def _portable_p2rank_output_dir(package_dir: Path, pdb_id: str) -> Path:
    return package_dir / "p2rank_outputs" / pdb_id


def _portable_fpocket_pockets_dir(package_dir: Path, pdb_id: str) -> Path:
    return package_dir / "fpocket_runs" / pdb_id / f"{pdb_id}_out" / "pockets"


def _find_pdb_input(row: dict[str, Any], package_dir: Path, pdb_id: str) -> tuple[str, str, str]:
    candidates = [
        item
        for item in [
            _candidate(_portable_pdb_path(package_dir, pdb_id), "package_portable"),
            _candidate(package_dir / "fpocket_runs" / pdb_id / f"{pdb_id}.pdb", "package_fpocket_run"),
            _candidate(_manifest_path(row, "tool_input_pdb_path", package_dir), "manifest_tool_input_pdb_path"),
            _candidate(_manifest_path(row, "fpocket_run_pdb_path", package_dir), "manifest_fpocket_run_pdb_path"),
        ]
        if item is not None
    ]
    existing = _first_existing(candidates)
    if existing:
        path, source = existing
        return "ready", str(path), source
    missing_path, missing_source = _preferred_missing(candidates, package_dir)
    return "missing", missing_path, missing_source


def _find_p2rank_predictions(row: dict[str, Any], package_dir: Path, pdb_id: str) -> tuple[str, str, str]:
    portable_expected = _portable_p2rank_output_dir(package_dir, pdb_id) / f"{pdb_id}.pdb_predictions.csv"
    expected_candidates = [
        item
        for item in [
            _candidate(portable_expected, "package_portable"),
            _candidate(_manifest_path(row, "expected_p2rank_predictions_csv", package_dir), "manifest_expected_p2rank_predictions_csv"),
        ]
        if item is not None
    ]
    existing_expected = _first_existing(expected_candidates)
    if existing_expected:
        path, source = existing_expected
        return "ready", str(path), source

    output_dirs = [
        item
        for item in [
            _candidate(_portable_p2rank_output_dir(package_dir, pdb_id), "package_portable_output_dir"),
            _candidate(_manifest_path(row, "p2rank_output_dir", package_dir), "manifest_p2rank_output_dir"),
        ]
        if item is not None
    ]
    for output_dir, source in _dedupe_candidates(output_dirs):
        if not output_dir.exists():
            continue
        matches: list[Path] = []
        for pattern in ("**/*_predictions.csv", "**/*predictions.csv", "**/predictions.csv"):
            matches.extend(sorted(output_dir.glob(pattern)))
        if matches:
            return "ready_nonstandard_name", str(matches[0]), source
    missing_path, missing_source = _preferred_missing(expected_candidates, package_dir)
    return "missing_output", missing_path, missing_source


def _find_fpocket_pockets(row: dict[str, Any], package_dir: Path, pdb_id: str) -> tuple[str, int, str, str]:
    candidates = [
        item
        for item in [
            _candidate(_portable_fpocket_pockets_dir(package_dir, pdb_id), "package_portable"),
            _candidate(_manifest_path(row, "expected_fpocket_pockets_dir", package_dir), "manifest_expected_fpocket_pockets_dir"),
        ]
        if item is not None
    ]
    for pockets_dir, source in _dedupe_candidates(candidates):
        if not pockets_dir.exists():
            continue
        pocket_files = sorted(pockets_dir.glob("pocket*_atm.pdb"))
        if pocket_files:
            return "ready", len(pocket_files), str(pockets_dir), source
        return "missing_pocket_files", 0, str(pockets_dir), source
    missing_path, missing_source = _preferred_missing(candidates, package_dir)
    return "missing_output_dir", 0, missing_path, missing_source


def _tool_status(command: str) -> dict[str, Any]:
    resolved = shutil.which(command)
    return {
        "command": command,
        "available": bool(resolved),
        "path": resolved or "",
    }


def _build_rows(manifest_rows: list[dict[str, str]], package_dir: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in manifest_rows:
        pdb_id = str(row.get("pdb_id") or "").strip().upper()
        methods = _normalize_methods(row.get("desired_methods"))
        pdb_status, pdb_path, pdb_source = _find_pdb_input(row, package_dir, pdb_id)
        if "p2rank" in methods:
            p2rank_status, p2rank_path, p2rank_source = _find_p2rank_predictions(row, package_dir, pdb_id)
        else:
            p2rank_status, p2rank_path, p2rank_source = "not_requested", "", ""
        if "fpocket" in methods:
            fpocket_status, fpocket_count, fpocket_dir, fpocket_source = _find_fpocket_pockets(row, package_dir, pdb_id)
        else:
            fpocket_status, fpocket_count, fpocket_dir, fpocket_source = "not_requested", 0, "", ""
        rows.append(
            {
                "pdb_id": pdb_id,
                "desired_methods": ",".join(methods),
                "pdb_input_status": pdb_status,
                "pdb_input_path": pdb_path,
                "pdb_input_source": pdb_source,
                "p2rank_status": p2rank_status,
                "p2rank_predictions_csv": p2rank_path,
                "p2rank_source": p2rank_source,
                "fpocket_status": fpocket_status,
                "fpocket_pocket_count": fpocket_count,
                "fpocket_pockets_dir": fpocket_dir,
                "fpocket_source": fpocket_source,
                "notes": str(row.get("notes") or ""),
            }
        )
    return rows


def _count(rows: list[dict[str, Any]], key: str, value: str) -> int:
    return sum(1 for row in rows if row.get(key) == value)


def _build_next_actions(summary: dict[str, Any]) -> list[str]:
    actions: list[str] = []
    p2rank_missing = int(summary["p2rank_missing_output_count"])
    fpocket_missing = int(summary["fpocket_missing_output_count"])
    if p2rank_missing and not summary["tools"]["p2rank"]["available"]:
        actions.append("P2Rank command is not available on PATH; install P2Rank or run run_p2rank_templates.ps1 on another machine, then copy outputs back.")
    elif p2rank_missing:
        actions.append("P2Rank command is available; run benchmarks/cd38/external_tool_inputs/run_p2rank_templates.ps1 to create missing predictions CSV files.")

    if fpocket_missing and not summary["tools"]["fpocket"]["available"]:
        actions.append("fpocket command is not available on PATH; install fpocket or run run_fpocket_templates.ps1 on another machine, then copy outputs back.")
    elif fpocket_missing:
        actions.append("fpocket command is available; run benchmarks/cd38/external_tool_inputs/run_fpocket_templates.ps1 to create missing pocket*_atm.pdb files.")

    if not p2rank_missing and not fpocket_missing:
        actions.append("External P2Rank/fpocket outputs appear ready; run refresh_readiness_after_external_tools.ps1 or refresh_cd38_benchmark_readiness.py with the package output roots.")
    else:
        actions.append("After external tools finish, run benchmarks/cd38/external_tool_inputs/refresh_readiness_after_external_tools.ps1.")
    return actions


def _md(value: Any) -> str:
    return str(value).replace("|", "\\|")


def _build_report(rows: list[dict[str, Any]], summary: dict[str, Any]) -> str:
    lines = [
        "# CD38 External Pocket Tool Preflight",
        "",
        "This report checks whether the CD38 external-tool input package has local tool commands and expected P2Rank/fpocket outputs.",
        "",
        "## Summary",
        "",
        f"- Package directory: `{summary['package_dir']}`",
        f"- Manifest rows: `{summary['manifest_row_count']}`",
        f"- Path resolution: `{summary['path_resolution']}`",
        f"- P2Rank command available: `{summary['tools']['p2rank']['available']}`",
        f"- P2Rank command path: `{summary['tools']['p2rank']['path']}`",
        f"- fpocket command available: `{summary['tools']['fpocket']['available']}`",
        f"- fpocket command path: `{summary['tools']['fpocket']['path']}`",
        f"- Missing P2Rank outputs: `{summary['p2rank_missing_output_count']}`",
        f"- Missing fpocket outputs: `{summary['fpocket_missing_output_count']}`",
        "",
        "## Next Actions",
        "",
    ]
    for action in summary["next_actions"]:
        lines.append(f"- {action}")
    lines.extend(
        [
            "",
        "## Per-Structure Status",
        "",
        "| PDB ID | Methods | PDB Input | PDB Source | P2Rank | P2Rank Source | fpocket | fpocket Source | fpocket pockets |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | ---: |",
        ]
    )
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(row["pdb_id"]),
                    _md(row["desired_methods"]),
                    _md(row["pdb_input_status"]),
                    _md(row["pdb_input_source"]),
                    _md(row["p2rank_status"]),
                    _md(row["p2rank_source"]),
                    _md(row["fpocket_status"]),
                    _md(row["fpocket_source"]),
                    _md(row["fpocket_pocket_count"]),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = _build_parser().parse_args()
    package_dir = Path(args.package_dir).expanduser().resolve()
    manifest_csv = Path(args.manifest_csv).expanduser().resolve() if args.manifest_csv else package_dir / "cd38_external_tool_input_manifest.csv"
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else package_dir / "preflight"
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_rows = _read_csv(manifest_csv)
    rows = _build_rows(manifest_rows, package_dir)
    p2rank_missing = sum(1 for row in rows if row["p2rank_status"] in {"missing_output", "missing_output_dir"})
    fpocket_missing = sum(1 for row in rows if row["fpocket_status"] in {"missing_output_dir", "missing_pocket_files"})
    summary: dict[str, Any] = {
        "package_dir": str(package_dir),
        "manifest_csv": str(manifest_csv),
        "out_dir": str(out_dir),
        "path_resolution": "package_portable_first",
        "manifest_row_count": len(manifest_rows),
        "pdb_input_ready_count": _count(rows, "pdb_input_status", "ready"),
        "p2rank_ready_count": sum(1 for row in rows if str(row["p2rank_status"]).startswith("ready")),
        "p2rank_missing_output_count": p2rank_missing,
        "fpocket_ready_count": _count(rows, "fpocket_status", "ready"),
        "fpocket_missing_output_count": fpocket_missing,
        "tools": {
            "p2rank": _tool_status(str(args.p2rank_command)),
            "fpocket": _tool_status(str(args.fpocket_command)),
        },
    }
    summary["next_actions"] = _build_next_actions(summary)

    status_csv = out_dir / "cd38_external_tool_preflight_status.csv"
    summary_json = out_dir / "cd38_external_tool_preflight_summary.json"
    report_md = out_dir / "cd38_external_tool_preflight_report.md"
    _write_csv(status_csv, rows, OUTPUT_COLUMNS)
    summary_json.write_text(json.dumps(summary, ensure_ascii=True, indent=2), encoding="utf-8")
    report_md.write_text(_build_report(rows, summary), encoding="utf-8")

    print(f"Saved: {status_csv}")
    print(f"Saved: {summary_json}")
    print(f"Saved: {report_md}")
    print(f"P2Rank available: {summary['tools']['p2rank']['available']}")
    print(f"fpocket available: {summary['tools']['fpocket']['available']}")
    print(f"Missing P2Rank outputs: {p2rank_missing}")
    print(f"Missing fpocket outputs: {fpocket_missing}")


if __name__ == "__main__":
    main()
