from __future__ import annotations

import argparse
import csv
import json
import shutil
import zipfile
from pathlib import Path
from typing import Any


MANIFEST_COLUMNS = [
    "status",
    "archive_or_source_path",
    "package_relative_path",
    "target_path",
    "size_bytes",
    "role",
    "pdb_id",
    "output_kind",
    "reason",
]

SCAN_COLUMNS = [
    "scan_status",
    "archive_or_source_path",
    "package_relative_path",
    "size_bytes",
    "role",
    "reason",
]

COVERAGE_COLUMNS = [
    "pdb_id",
    "method",
    "expected",
    "status",
    "candidate_count",
    "matched_relative_paths",
    "notes",
]

REPAIR_PLAN_COLUMNS = [
    "pdb_id",
    "method",
    "coverage_status",
    "expected_return_path",
    "required_pattern",
    "generated_by",
    "suggested_action",
    "copy_back_instruction",
    "validation_command",
    "notes",
]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Import returned CD38 external P2Rank/fpocket outputs back into the local external_tool_inputs package."
    )
    parser.add_argument(
        "--source",
        required=True,
        help="Returned zip or directory containing external_tool_inputs with p2rank_outputs/ and/or fpocket_runs/*/*_out/.",
    )
    parser.add_argument(
        "--package_dir",
        default="benchmarks/cd38/external_tool_inputs",
        help="Local package directory generated by prepare_cd38_external_tool_inputs.py.",
    )
    parser.add_argument("--out_dir", default=None, help="Output report directory. Defaults to <package_dir>/imported_outputs.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing imported output files.")
    parser.add_argument("--dry_run", action="store_true", help="Only report what would be imported.")
    return parser


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return [dict(row) for row in csv.DictReader(f)]


def _split_methods(value: Any) -> list[str]:
    methods: list[str] = []
    for part in str(value or "").split(","):
        method = part.strip().lower().replace("-", "_")
        if method and method not in methods:
            methods.append(method)
    return methods


def _is_importable_relative_path(relative_path: Path) -> bool:
    return _importable_reason(relative_path)[0]


def _importable_reason(relative_path: Path) -> tuple[bool, str]:
    parts = relative_path.parts
    if len(parts) < 2:
        return False, "too_shallow"
    if parts[0] == "p2rank_outputs" and relative_path.name:
        return True, ""
    if parts[0] == "fpocket_runs" and any(part.endswith("_out") for part in parts):
        return True, ""
    if parts[0] == "fpocket_runs":
        return False, "fpocket_runs_without_out_dir"
    return False, "not_p2rank_or_fpocket_output"


def _strip_to_package_relative(path: str) -> Path | None:
    raw = Path(path.replace("\\", "/"))
    parts = raw.parts
    if "external_tool_inputs" in parts:
        index = parts.index("external_tool_inputs") + 1
        if index >= len(parts):
            return None
        return Path(*parts[index:])
    for marker in ("p2rank_outputs", "fpocket_runs"):
        if marker in parts:
            return Path(*parts[parts.index(marker) :])
    return raw


def _role(relative_path: Path) -> str:
    if relative_path.parts and relative_path.parts[0] == "p2rank_outputs":
        return "p2rank_output"
    if relative_path.parts and relative_path.parts[0] == "fpocket_runs":
        return "fpocket_output"
    return "other"


def _pdb_id_from_relative_path(relative_path: Path) -> str:
    parts = relative_path.parts
    if len(parts) >= 2 and parts[0] in {"p2rank_outputs", "fpocket_runs"}:
        return parts[1].upper()
    return ""


def _output_kind(relative_path: Path) -> str:
    parts = relative_path.parts
    name = relative_path.name.lower()
    if parts and parts[0] == "p2rank_outputs":
        if name.endswith(".csv") and "prediction" in name:
            return "p2rank_predictions_csv"
        return "p2rank_other"
    if parts and parts[0] == "fpocket_runs":
        if name.startswith("pocket") and name.endswith("_atm.pdb"):
            return "fpocket_pocket_atm"
        return "fpocket_other"
    return "other"


def _safe_target(package_dir: Path, relative_path: Path) -> Path:
    package_root = package_dir.resolve()
    target = (package_root / relative_path).resolve()
    if package_root != target and package_root not in target.parents:
        raise ValueError(f"Unsafe target path outside package directory: {target}")
    return target


def _copy_file(source: Path, target: Path, *, overwrite: bool, dry_run: bool) -> tuple[str, str]:
    if target.exists() and not overwrite:
        return "skipped_existing", "target_exists"
    if dry_run:
        return "dry_run", ""
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)
    return "imported", ""


def _scan_row(
    *,
    status: str,
    source_path: str,
    relative_path: Path | None,
    size_bytes: int,
    reason: str = "",
) -> dict[str, Any]:
    return {
        "scan_status": status,
        "archive_or_source_path": source_path,
        "package_relative_path": "" if relative_path is None else relative_path.as_posix(),
        "size_bytes": size_bytes,
        "role": "" if relative_path is None else _role(relative_path),
        "reason": reason,
    }


def _source_overview(source: Path) -> dict[str, Any]:
    if source.is_dir():
        file_count = sum(1 for path in source.rglob("*") if path.is_file())
        top_entries = sorted(path.name for path in source.iterdir())
        return {
            "source_type": "directory",
            "source_file_count": int(file_count),
            "source_top_level_entries": top_entries[:50],
        }
    if zipfile.is_zipfile(source):
        with zipfile.ZipFile(source) as zf:
            infos = [info for info in zf.infolist() if not info.is_dir()]
            top_entries = sorted({Path(info.filename.replace("\\", "/")).parts[0] for info in infos if Path(info.filename.replace("\\", "/")).parts})
        return {
            "source_type": "zip",
            "source_file_count": int(len(infos)),
            "source_top_level_entries": top_entries[:50],
        }
    return {
        "source_type": "unknown",
        "source_file_count": 0,
        "source_top_level_entries": [],
    }


def _first_part(value: Any) -> str:
    path = Path(str(value or "").replace("\\", "/"))
    return path.parts[0] if path.parts else ""


def _has_scan_path(scan_rows: list[dict[str, Any]], prefix: str) -> bool:
    return any(_first_part(row.get("package_relative_path")) == prefix for row in scan_rows)


def _has_run_template_or_manifest(scan_rows: list[dict[str, Any]]) -> bool:
    for row in scan_rows:
        name = Path(str(row.get("package_relative_path") or "").replace("\\", "/")).name
        if name.startswith("run_") or name in {
            "TRANSFER_README.md",
            "cd38_external_tool_input_manifest.csv",
            "cd38_external_tool_inputs.md",
        }:
            return True
    return False


def _diagnose_source(
    *,
    candidate_count: int,
    source_file_count: int,
    ignored_reason_counts: dict[str, int],
    scan_rows: list[dict[str, Any]],
) -> tuple[str, str]:
    if candidate_count:
        return (
            "candidate_outputs_found",
            "Importable P2Rank/fpocket output files were found. Review the import manifest before running finalize with --run_discovered.",
        )
    if not source_file_count:
        return (
            "empty_source",
            "The returned source contains no files. Check that the zip/directory was created after running P2Rank/fpocket.",
        )
    has_pdb_inputs = _has_scan_path(scan_rows, "pdbs")
    has_templates = _has_run_template_or_manifest(scan_rows)
    has_fpocket_inputs_only = int(ignored_reason_counts.get("fpocket_runs_without_out_dir") or 0) > 0
    if has_templates and (has_pdb_inputs or has_fpocket_inputs_only):
        return (
            "input_package_without_external_outputs",
            "This looks like the original external-tool input package, not a completed return package. Run P2Rank/fpocket first, then return p2rank_outputs/ and fpocket_runs/*/*_out/.",
        )
    if has_fpocket_inputs_only:
        return (
            "fpocket_input_pdbs_without_outputs",
            "fpocket run folders contain input PDB files but no *_out/pockets/pocket*_atm.pdb outputs. Run fpocket before importing.",
        )
    if int(ignored_reason_counts.get("not_p2rank_or_fpocket_output") or 0) == source_file_count:
        return (
            "wrong_folder_shape",
            "Files were scanned, but none were under p2rank_outputs/ or fpocket_runs/*/*_out/. Check the returned folder layout.",
        )
    return (
        "no_supported_output_files_found",
        "No importable P2Rank/fpocket output files were found. Open the scan CSV for ignored paths and reasons.",
    )


def _import_from_directory(
    source_dir: Path, package_dir: Path, *, overwrite: bool, dry_run: bool
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    scan_rows: list[dict[str, Any]] = []
    roots: list[Path] = []
    if (source_dir / "external_tool_inputs").is_dir():
        roots.append(source_dir / "external_tool_inputs")
    roots.append(source_dir)

    seen: set[Path] = set()
    for root in roots:
        if not root.exists():
            continue
        for source_file in sorted(path for path in root.rglob("*") if path.is_file()):
            relative_path = _strip_to_package_relative(source_file.relative_to(root).as_posix())
            if relative_path is None:
                scan_rows.append(
                    _scan_row(
                        status="ignored",
                        source_path=str(source_file),
                        relative_path=None,
                        size_bytes=int(source_file.stat().st_size),
                        reason="empty_package_relative_path",
                    )
                )
                continue
            if relative_path in seen:
                scan_rows.append(
                    _scan_row(
                        status="ignored_duplicate",
                        source_path=str(source_file),
                        relative_path=relative_path,
                        size_bytes=int(source_file.stat().st_size),
                        reason="duplicate_package_relative_path",
                    )
                )
                continue
            importable, reason = _importable_reason(relative_path)
            if not importable:
                scan_rows.append(
                    _scan_row(
                        status="ignored",
                        source_path=str(source_file),
                        relative_path=relative_path,
                        size_bytes=int(source_file.stat().st_size),
                        reason=reason,
                    )
                )
                continue
            seen.add(relative_path)
            target = _safe_target(package_dir, relative_path)
            status, reason = _copy_file(source_file, target, overwrite=overwrite, dry_run=dry_run)
            scan_rows.append(
                _scan_row(
                    status="candidate",
                    source_path=str(source_file),
                    relative_path=relative_path,
                    size_bytes=int(source_file.stat().st_size),
                )
            )
            rows.append(
                {
                    "status": status,
                    "archive_or_source_path": str(source_file),
                    "package_relative_path": relative_path.as_posix(),
                    "target_path": str(target),
                    "size_bytes": int(source_file.stat().st_size),
                    "role": _role(relative_path),
                    "pdb_id": _pdb_id_from_relative_path(relative_path),
                    "output_kind": _output_kind(relative_path),
                    "reason": reason,
                }
            )
    return rows, scan_rows


def _import_from_zip(
    source_zip: Path, package_dir: Path, *, overwrite: bool, dry_run: bool
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    scan_rows: list[dict[str, Any]] = []
    seen: set[Path] = set()
    with zipfile.ZipFile(source_zip) as zf:
        for info in sorted(zf.infolist(), key=lambda item: item.filename):
            if info.is_dir():
                continue
            relative_path = _strip_to_package_relative(info.filename)
            if relative_path is None:
                scan_rows.append(
                    _scan_row(
                        status="ignored",
                        source_path=info.filename,
                        relative_path=None,
                        size_bytes=int(info.file_size),
                        reason="empty_package_relative_path",
                    )
                )
                continue
            if relative_path in seen:
                scan_rows.append(
                    _scan_row(
                        status="ignored_duplicate",
                        source_path=info.filename,
                        relative_path=relative_path,
                        size_bytes=int(info.file_size),
                        reason="duplicate_package_relative_path",
                    )
                )
                continue
            importable, reason = _importable_reason(relative_path)
            if not importable:
                scan_rows.append(
                    _scan_row(
                        status="ignored",
                        source_path=info.filename,
                        relative_path=relative_path,
                        size_bytes=int(info.file_size),
                        reason=reason,
                    )
                )
                continue
            seen.add(relative_path)
            target = _safe_target(package_dir, relative_path)
            if target.exists() and not overwrite:
                status, reason = "skipped_existing", "target_exists"
            elif dry_run:
                status, reason = "dry_run", ""
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                with zf.open(info) as src, target.open("wb") as dst:
                    shutil.copyfileobj(src, dst)
                status, reason = "imported", ""
            scan_rows.append(
                _scan_row(
                    status="candidate",
                    source_path=info.filename,
                    relative_path=relative_path,
                    size_bytes=int(info.file_size),
                )
            )
            rows.append(
                {
                    "status": status,
                    "archive_or_source_path": info.filename,
                    "package_relative_path": relative_path.as_posix(),
                    "target_path": str(target),
                    "size_bytes": int(info.file_size),
                    "role": _role(relative_path),
                    "pdb_id": _pdb_id_from_relative_path(relative_path),
                    "output_kind": _output_kind(relative_path),
                    "reason": reason,
                }
            )
    return rows, scan_rows


def _build_coverage_rows(package_dir: Path, rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    manifest_rows = _read_csv(package_dir / "cd38_external_tool_input_manifest.csv")
    coverage_rows: list[dict[str, Any]] = []
    expected_pairs: set[tuple[str, str]] = set()
    for manifest_row in manifest_rows:
        enabled = str(manifest_row.get("enabled") or "true").strip().lower()
        if enabled in {"false", "0", "no"}:
            continue
        pdb_id = str(manifest_row.get("pdb_id") or "").strip().upper()
        if not pdb_id:
            continue
        methods = _split_methods(manifest_row.get("desired_methods"))
        for method in ("p2rank", "fpocket"):
            if method not in methods:
                continue
            expected_pairs.add((pdb_id, method))
            output_kind = "p2rank_predictions_csv" if method == "p2rank" else "fpocket_pocket_atm"
            matched = [
                str(row.get("package_relative_path") or "")
                for row in rows
                if str(row.get("pdb_id") or "").upper() == pdb_id and str(row.get("output_kind") or "") == output_kind
            ]
            coverage_rows.append(
                {
                    "pdb_id": pdb_id,
                    "method": method,
                    "expected": "true",
                    "status": "ready_from_return" if matched else "missing_from_return",
                    "candidate_count": len(matched),
                    "matched_relative_paths": ";".join(sorted(matched)),
                    "notes": "",
                }
            )
    seen_unexpected: set[tuple[str, str]] = set()
    for row in rows:
        pdb_id = str(row.get("pdb_id") or "").upper()
        output_kind = str(row.get("output_kind") or "")
        method = "p2rank" if output_kind == "p2rank_predictions_csv" else "fpocket" if output_kind == "fpocket_pocket_atm" else ""
        if not pdb_id or not method or (pdb_id, method) in expected_pairs or (pdb_id, method) in seen_unexpected:
            continue
        seen_unexpected.add((pdb_id, method))
        matched = [
            str(item.get("package_relative_path") or "")
            for item in rows
            if str(item.get("pdb_id") or "").upper() == pdb_id
            and str(item.get("output_kind") or "") == output_kind
        ]
        coverage_rows.append(
            {
                "pdb_id": pdb_id,
                "method": method,
                "expected": "false",
                "status": "unexpected_return_output",
                "candidate_count": len(matched),
                "matched_relative_paths": ";".join(sorted(matched)),
                "notes": "Output was present in the returned source but not requested by the package manifest.",
            }
        )
    return coverage_rows


def _coverage_summary(coverage_rows: list[dict[str, Any]]) -> dict[str, Any]:
    expected_rows = [row for row in coverage_rows if str(row.get("expected") or "").lower() == "true"]
    ready_rows = [row for row in expected_rows if row.get("status") == "ready_from_return"]
    missing_rows = [row for row in expected_rows if row.get("status") == "missing_from_return"]
    unexpected_rows = [row for row in coverage_rows if row.get("status") == "unexpected_return_output"]
    missing_expected_outputs = [f"{row.get('pdb_id')}:{row.get('method')}" for row in missing_rows]
    ready_expected_outputs = [f"{row.get('pdb_id')}:{row.get('method')}" for row in ready_rows]
    unexpected_outputs = [f"{row.get('pdb_id')}:{row.get('method')}" for row in unexpected_rows]
    return {
        "expected_output_count": len(expected_rows),
        "ready_expected_output_count": len(ready_rows),
        "missing_expected_output_count": len(missing_rows),
        "unexpected_output_count": len(unexpected_rows),
        "ready_expected_outputs": ready_expected_outputs,
        "missing_expected_outputs": missing_expected_outputs,
        "unexpected_outputs": unexpected_outputs,
    }


def _read_expected_return_map(package_dir: Path) -> dict[tuple[str, str], dict[str, str]]:
    rows = _read_csv(package_dir / "cd38_external_tool_expected_returns.csv")
    expected: dict[tuple[str, str], dict[str, str]] = {}
    for row in rows:
        pdb_id = str(row.get("pdb_id") or "").strip().upper()
        method = str(row.get("method") or "").strip().lower()
        if pdb_id and method:
            expected[(pdb_id, method)] = row
    return expected


def _fallback_expected_return_path(pdb_id: str, method: str) -> str:
    if method == "p2rank":
        return f"p2rank_outputs/{pdb_id}/{pdb_id}.pdb_predictions.csv"
    if method == "fpocket":
        return f"fpocket_runs/{pdb_id}/{pdb_id}_out/pockets/pocket*_atm.pdb"
    return ""


def _fallback_required_pattern(pdb_id: str, method: str) -> str:
    if method == "p2rank":
        return f"p2rank_outputs/{pdb_id}/*_predictions.csv"
    if method == "fpocket":
        return f"fpocket_runs/{pdb_id}/{pdb_id}_out/pockets/pocket*_atm.pdb"
    return ""


def _suggested_repair_action(pdb_id: str, method: str) -> str:
    if method == "p2rank":
        return f"Run run_p2rank_templates.ps1 or run_p2rank_templates.sh, then confirm {pdb_id}.pdb_predictions.csv exists."
    if method == "fpocket":
        return f"Run run_fpocket_templates.ps1 or run_fpocket_templates.sh, then confirm at least one pocket*_atm.pdb exists for {pdb_id}."
    return "Generate the missing external-tool output and return it under the expected package-relative path."


def _build_repair_plan_rows(package_dir: Path, coverage_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    expected_map = _read_expected_return_map(package_dir)
    rows: list[dict[str, Any]] = []
    for coverage_row in coverage_rows:
        if str(coverage_row.get("expected") or "").lower() != "true":
            continue
        if coverage_row.get("status") == "ready_from_return":
            continue
        pdb_id = str(coverage_row.get("pdb_id") or "").strip().upper()
        method = str(coverage_row.get("method") or "").strip().lower()
        if not pdb_id or not method:
            continue
        expected_row = expected_map.get((pdb_id, method), {})
        expected_return_path = str(expected_row.get("expected_return_path") or _fallback_expected_return_path(pdb_id, method))
        required_pattern = str(expected_row.get("required_pattern") or _fallback_required_pattern(pdb_id, method))
        generated_by = str(
            expected_row.get("generated_by")
            or (
                "run_p2rank_templates.ps1 or run_p2rank_templates.sh"
                if method == "p2rank"
                else "run_fpocket_templates.ps1 or run_fpocket_templates.sh"
            )
        )
        rows.append(
            {
                "pdb_id": pdb_id,
                "method": method,
                "coverage_status": str(coverage_row.get("status") or ""),
                "expected_return_path": expected_return_path,
                "required_pattern": required_pattern,
                "generated_by": generated_by,
                "suggested_action": _suggested_repair_action(pdb_id, method),
                "copy_back_instruction": "Return the whole completed package folder/zip, or copy this path back under benchmarks/cd38/external_tool_inputs/.",
                "validation_command": "python import_cd38_external_tool_outputs.py --source <returned_zip_or_dir> --dry_run",
                "notes": str(expected_row.get("notes") or coverage_row.get("notes") or ""),
            }
        )
    return rows


def _build_summary(
    rows: list[dict[str, Any]],
    scan_rows: list[dict[str, Any]],
    coverage_rows: list[dict[str, Any]],
    repair_plan_rows: list[dict[str, Any]],
    args: argparse.Namespace,
    source: Path,
    package_dir: Path,
    out_dir: Path,
) -> dict[str, Any]:
    status_counts: dict[str, int] = {}
    role_counts: dict[str, int] = {}
    scan_status_counts: dict[str, int] = {}
    ignored_reason_counts: dict[str, int] = {}
    for row in rows:
        status = str(row.get("status") or "")
        role = str(row.get("role") or "")
        status_counts[status] = status_counts.get(status, 0) + 1
        role_counts[role] = role_counts.get(role, 0) + 1
    for row in scan_rows:
        status = str(row.get("scan_status") or "")
        reason = str(row.get("reason") or "")
        scan_status_counts[status] = scan_status_counts.get(status, 0) + 1
        if status.startswith("ignored") and reason:
            ignored_reason_counts[reason] = ignored_reason_counts.get(reason, 0) + 1
    overview = _source_overview(source)
    candidate_count = int(len(rows))
    diagnosis, diagnostic_message = _diagnose_source(
        candidate_count=candidate_count,
        source_file_count=int(overview["source_file_count"]),
        ignored_reason_counts=ignored_reason_counts,
        scan_rows=scan_rows,
    )
    coverage = _coverage_summary(coverage_rows)
    return {
        "source": str(source),
        "source_type": overview["source_type"],
        "source_file_count": overview["source_file_count"],
        "source_top_level_entries": overview["source_top_level_entries"],
        "source_diagnosis": diagnosis,
        "diagnostic_message": diagnostic_message,
        "package_dir": str(package_dir),
        "out_dir": str(out_dir),
        "dry_run": bool(args.dry_run),
        "overwrite": bool(args.overwrite),
        "scanned_file_count": int(len(scan_rows)),
        "candidate_file_count": candidate_count,
        "ignored_file_count": int(sum(1 for row in scan_rows if str(row.get("scan_status") or "").startswith("ignored"))),
        "imported_count": int(status_counts.get("imported", 0)),
        "dry_run_count": int(status_counts.get("dry_run", 0)),
        "skipped_existing_count": int(status_counts.get("skipped_existing", 0)),
        "status_counts": status_counts,
        "role_counts": role_counts,
        "scan_status_counts": scan_status_counts,
        "ignored_reason_counts": ignored_reason_counts,
        "coverage": coverage,
        "missing_repair_action_count": int(len(repair_plan_rows)),
        "manifest_csv": str(out_dir / "cd38_external_tool_output_import_manifest.csv"),
        "scan_csv": str(out_dir / "cd38_external_tool_output_import_scan.csv"),
        "coverage_csv": str(out_dir / "cd38_external_tool_output_import_coverage.csv"),
        "repair_plan_csv": str(out_dir / "cd38_external_tool_output_import_repair_plan.csv"),
        "summary_json": str(out_dir / "cd38_external_tool_output_import_summary.json"),
        "report_md": str(out_dir / "cd38_external_tool_output_import_report.md"),
    }


def _build_report(summary: dict[str, Any]) -> str:
    lines = [
        "# CD38 External Tool Output Import",
        "",
        f"- Source: `{summary['source']}`",
        f"- Source type: `{summary['source_type']}`",
        f"- Source diagnosis: `{summary['source_diagnosis']}`",
        f"- Diagnostic message: {summary['diagnostic_message']}",
        f"- Source files scanned: `{summary['source_file_count']}`",
        f"- Package directory: `{summary['package_dir']}`",
        f"- Dry run: `{summary['dry_run']}`",
        f"- Overwrite: `{summary['overwrite']}`",
        f"- Candidate output files: `{summary['candidate_file_count']}`",
        f"- Expected outputs ready from return: `{summary['coverage']['ready_expected_output_count']}/{summary['coverage']['expected_output_count']}`",
        f"- Missing expected outputs: `{summary['coverage']['missing_expected_output_count']}`",
        f"- Repair actions: `{summary['missing_repair_action_count']}`",
        f"- Unexpected returned outputs: `{summary['coverage']['unexpected_output_count']}`",
        f"- Ignored files: `{summary['ignored_file_count']}`",
        f"- Imported files: `{summary['imported_count']}`",
        f"- Skipped existing files: `{summary['skipped_existing_count']}`",
        "",
        "## Source Top-Level Entries",
        "",
    ]
    top_entries = list(summary.get("source_top_level_entries") or [])
    if top_entries:
        for entry in top_entries:
            lines.append(f"- `{entry}`")
    else:
        lines.append("- No top-level entries were detected.")
    lines.extend(
        [
            "",
            "## Scan Status Counts",
            "",
        ]
    )
    for status, count in sorted((summary.get("scan_status_counts") or {}).items()):
        lines.append(f"- `{status}`: `{count}`")
    if not summary.get("scan_status_counts"):
        lines.append("- No files were scanned.")
    lines.extend(
        [
            "",
            "## Ignored Reason Counts",
            "",
        ]
    )
    if summary["ignored_reason_counts"]:
        for reason, count in sorted(summary["ignored_reason_counts"].items()):
            lines.append(f"- `{reason}`: `{count}`")
    else:
        lines.append("- No ignored files.")
    lines.extend(
        [
            "",
        "## Role Counts",
        "",
        ]
    )
    if summary["role_counts"]:
        for role, count in sorted(summary["role_counts"].items()):
            lines.append(f"- `{role}`: `{count}`")
    else:
        lines.append("- No importable P2Rank/fpocket output files were found.")
    lines.extend(
        [
            "",
            "## Expected Coverage",
            "",
        ]
    )
    coverage = summary.get("coverage") or {}
    ready_outputs = coverage.get("ready_expected_outputs") or []
    missing_outputs = coverage.get("missing_expected_outputs") or []
    unexpected_outputs = coverage.get("unexpected_outputs") or []
    lines.append(f"- Ready expected outputs: `{coverage.get('ready_expected_output_count', 0)}/{coverage.get('expected_output_count', 0)}`")
    if ready_outputs:
        lines.append(f"- Ready: `{', '.join(ready_outputs)}`")
    if missing_outputs:
        lines.append(f"- Missing: `{', '.join(missing_outputs)}`")
    if unexpected_outputs:
        lines.append(f"- Unexpected: `{', '.join(unexpected_outputs)}`")
    lines.extend(
        [
            "",
            "## Next Actions",
            "",
        ]
    )
    if int(summary["imported_count"]) or int(summary["dry_run_count"]):
        lines.append("- Run `python finalize_cd38_external_benchmark.py --run_discovered` after confirming the import manifest.")
    elif int(summary["skipped_existing_count"]):
        lines.append("- Files already exist locally. Rerun with `--overwrite` only if you intentionally want to replace them.")
    elif summary.get("source_diagnosis") == "input_package_without_external_outputs":
        lines.append("- This appears to be the original transfer/input package. Run P2Rank/fpocket on it first, then import the returned outputs.")
        lines.append("- Expected returned outputs: `p2rank_outputs/<PDB>/*_predictions.csv` and `fpocket_runs/<PDB>/<PDB>_out/pockets/pocket*_atm.pdb`.")
        lines.append(f"- Open the repair plan CSV for exact missing paths: `{summary['repair_plan_csv']}`.")
    else:
        lines.append("- Check that the source contains `p2rank_outputs/` or `fpocket_runs/*/*_out/`; these folders may be inside an `external_tool_inputs/` directory or one additional returned-folder wrapper.")
        lines.append("- Open the scan CSV to see ignored files and reasons.")
        if int(summary.get("missing_repair_action_count") or 0):
            lines.append(f"- Open the repair plan CSV for exact missing paths: `{summary['repair_plan_csv']}`.")
    lines.extend(
        [
            "",
            "## Outputs",
            "",
            f"- Import manifest: `{summary['manifest_csv']}`",
            f"- Scan manifest: `{summary['scan_csv']}`",
            f"- Coverage manifest: `{summary['coverage_csv']}`",
            f"- Repair plan: `{summary['repair_plan_csv']}`",
            f"- Summary JSON: `{summary['summary_json']}`",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    args = _build_parser().parse_args()
    source = Path(args.source).expanduser().resolve()
    package_dir = Path(args.package_dir).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else package_dir / "imported_outputs"
    if not source.exists():
        raise FileNotFoundError(f"Returned source not found: {source}")
    if not package_dir.exists():
        raise FileNotFoundError(f"Local package directory not found: {package_dir}")

    if source.is_dir():
        rows, scan_rows = _import_from_directory(source, package_dir, overwrite=bool(args.overwrite), dry_run=bool(args.dry_run))
    elif zipfile.is_zipfile(source):
        rows, scan_rows = _import_from_zip(source, package_dir, overwrite=bool(args.overwrite), dry_run=bool(args.dry_run))
    else:
        raise ValueError(f"Source must be a directory or zip file: {source}")

    out_dir.mkdir(parents=True, exist_ok=True)
    coverage_rows = _build_coverage_rows(package_dir, rows)
    repair_plan_rows = _build_repair_plan_rows(package_dir, coverage_rows)
    summary = _build_summary(rows, scan_rows, coverage_rows, repair_plan_rows, args, source, package_dir, out_dir)
    _write_csv(Path(summary["manifest_csv"]), rows, MANIFEST_COLUMNS)
    _write_csv(Path(summary["scan_csv"]), scan_rows, SCAN_COLUMNS)
    _write_csv(Path(summary["coverage_csv"]), coverage_rows, COVERAGE_COLUMNS)
    _write_csv(Path(summary["repair_plan_csv"]), repair_plan_rows, REPAIR_PLAN_COLUMNS)
    Path(summary["summary_json"]).write_text(json.dumps(summary, ensure_ascii=True, indent=2), encoding="utf-8")
    Path(summary["report_md"]).write_text(_build_report(summary), encoding="utf-8")

    print(f"Saved: {summary['manifest_csv']}")
    print(f"Saved: {summary['scan_csv']}")
    print(f"Saved: {summary['coverage_csv']}")
    print(f"Saved: {summary['repair_plan_csv']}")
    print(f"Saved: {summary['summary_json']}")
    print(f"Saved: {summary['report_md']}")
    print(f"Candidate output files: {summary['candidate_file_count']}")
    print(f"Imported files: {summary['imported_count']}")


if __name__ == "__main__":
    main()
