from __future__ import annotations

import argparse
import csv
import json
import zipfile
from pathlib import Path
from typing import Any


MANIFEST_COLUMNS = [
    "archive_path",
    "source_path",
    "size_bytes",
    "role",
]


ROOT_FILES = {
    "cd38_external_tool_input_manifest.csv": "manifest",
    "cd38_external_tool_expected_returns.csv": "expected_return_manifest",
    "cd38_external_tool_return_checklist.md": "return_checklist",
    "cd38_external_tool_inputs.md": "instructions",
    "cd38_external_tool_inputs_summary.json": "summary",
    "cd38_external_tool_next_run.md": "next_run_instructions",
    "cd38_external_tool_next_run_plan.csv": "next_run_plan",
    "cd38_external_tool_next_run_summary.json": "next_run_summary",
    "run_p2rank_templates.ps1": "windows_p2rank_runner",
    "run_fpocket_templates.ps1": "windows_fpocket_runner",
    "run_cd38_external_next_benchmark.ps1": "windows_next_run_runner",
    "run_p2rank_templates.sh": "bash_p2rank_runner",
    "run_fpocket_templates.sh": "bash_fpocket_runner",
    "run_cd38_external_next_benchmark.sh": "bash_next_run_runner",
    "check_external_tool_environment.ps1": "windows_preflight",
    "refresh_readiness_after_external_tools.ps1": "windows_readiness_refresh",
    "finalize_external_benchmark.ps1": "windows_finalize",
}


EXCLUDED_DIRS_DEFAULT = {
    "preflight",
    "finalize",
    "p2rank_outputs",
}


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Package the CD38 external-tool input directory into a transfer zip for another machine or WSL/Linux."
    )
    parser.add_argument(
        "--package_dir",
        default="benchmarks/cd38/external_tool_inputs",
        help="Directory generated by prepare_cd38_external_tool_inputs.py.",
    )
    parser.add_argument(
        "--out_dir",
        default="benchmarks/cd38/external_tool_transfer",
        help="Output directory for the transfer zip and reports.",
    )
    parser.add_argument("--out_zip", default=None, help="Optional explicit output zip path.")
    parser.add_argument(
        "--include_existing_outputs",
        action="store_true",
        help="Include existing p2rank_outputs and fpocket *_out directories. Default is to package inputs only.",
    )
    parser.add_argument(
        "--root_name",
        default=None,
        help="Top-level directory name inside the zip. Defaults to the package directory name.",
    )
    parser.add_argument(
        "--skip_runbook_refresh",
        action="store_true",
        help="Do not refresh cd38_external_tool_next_run.* before packaging.",
    )
    return parser


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _role_for_path(relative_path: Path) -> str:
    text = relative_path.as_posix()
    if len(relative_path.parts) == 1:
        return ROOT_FILES.get(relative_path.name, "root_file")
    if relative_path.parts[0] == "pdbs" and relative_path.suffix.lower() == ".pdb":
        return "p2rank_input_pdb"
    if relative_path.parts[0] == "fpocket_runs" and relative_path.suffix.lower() == ".pdb":
        return "fpocket_input_pdb"
    if "p2rank_outputs" in relative_path.parts:
        return "existing_p2rank_output"
    if any(part.endswith("_out") for part in relative_path.parts):
        return "existing_fpocket_output"
    return f"package_file:{text}"


def _include_file(relative_path: Path, *, include_existing_outputs: bool) -> bool:
    if any(part == "__pycache__" for part in relative_path.parts):
        return False
    if relative_path.suffix.lower() in {".zip", ".pyc"}:
        return False
    if len(relative_path.parts) == 1:
        return relative_path.name in ROOT_FILES
    if not include_existing_outputs:
        if relative_path.parts[0] in EXCLUDED_DIRS_DEFAULT:
            return False
        if any(part.endswith("_out") for part in relative_path.parts):
            return False
    if relative_path.parts[0] == "pdbs" and relative_path.suffix.lower() == ".pdb":
        return True
    if relative_path.parts[0] == "fpocket_runs" and relative_path.suffix.lower() == ".pdb":
        return True
    if include_existing_outputs and (
        relative_path.parts[0] == "p2rank_outputs" or any(part.endswith("_out") for part in relative_path.parts)
    ):
        return True
    return False


def _iter_package_files(package_dir: Path, *, include_existing_outputs: bool) -> list[Path]:
    files: list[Path] = []
    for path in sorted(package_dir.rglob("*")):
        if not path.is_file():
            continue
        relative_path = path.relative_to(package_dir)
        if _include_file(relative_path, include_existing_outputs=include_existing_outputs):
            files.append(path)
    return files


def _refresh_runbook(package_dir: Path) -> dict[str, Any]:
    try:
        from build_cd38_external_tool_runbook import build_cd38_external_tool_runbook

        payload = build_cd38_external_tool_runbook(package_dir=package_dir)
        summary = payload.get("summary") if isinstance(payload, dict) else {}
        if not isinstance(summary, dict):
            summary = {}
        outputs = summary.get("outputs") if isinstance(summary.get("outputs"), dict) else {}
        return {
            "status": "success",
            "selected_action_count": summary.get("selected_action_count", ""),
            "report_md": outputs.get("report_md", ""),
            "powershell_runner": outputs.get("powershell_runner", ""),
            "bash_runner": outputs.get("bash_runner", ""),
        }
    except Exception as exc:
        return {"status": "failed", "error": str(exc)}


def _transfer_readme(root_name: str) -> str:
    return "\n".join(
        [
            "# CD38 External Tool Transfer Package",
            "",
            "This zip contains the CD38 PDB inputs and command templates needed to run external P2Rank/fpocket tools.",
            "",
            "## Windows PowerShell",
            "",
            f"1. Unzip this archive and enter `{root_name}`.",
            "2. Prefer `run_cd38_external_next_benchmark.ps1`; it runs only the missing benchmark actions from the current action plan.",
            "3. If you intentionally want all template rows, run `run_p2rank_templates.ps1` and `run_fpocket_templates.ps1`.",
            "",
            "## Linux / WSL",
            "",
            f"1. Unzip this archive and enter `{root_name}`.",
            "2. Prefer `chmod +x run_cd38_external_next_benchmark.sh` and `./run_cd38_external_next_benchmark.sh`; it runs only the missing benchmark actions from the current action plan.",
            "3. If you intentionally want all template rows, run `./run_p2rank_templates.sh` and `./run_fpocket_templates.sh`.",
            "",
            "## Copy Back",
            "",
            "Preflight resolves package-local paths first, so the unzipped folder can be moved between machines without relying on absolute paths from the original project.",
            "",
            "After external tools finish, either copy these generated folders back into the original project package directory:",
            "",
            "- `p2rank_outputs/`",
            "- `fpocket_runs/*/*_out/`",
            "",
            "Use `cd38_external_tool_return_checklist.md` or `cd38_external_tool_expected_returns.csv` to confirm which PDB/method outputs are expected before zipping the returned folder.",
            "",
            "Or zip this whole returned folder and import it in the original project with:",
            "",
            "```bash",
            "python import_cd38_external_tool_outputs.py --source returned_external_tool_inputs.zip",
            "```",
            "",
            "The importer also handles one extra wrapper folder around `p2rank_outputs/` or `fpocket_runs/`, writes scan and coverage CSVs, and reports a source diagnosis such as `input_package_without_external_outputs`.",
            "",
            "Or let finalize import the returned package before checking readiness:",
            "",
            "```bash",
            "python finalize_cd38_external_benchmark.py --import_source returned_external_tool_inputs.zip --run_discovered",
            "```",
            "",
            "If you imported outputs separately, then finalize:",
            "",
            "```bash",
            "python finalize_cd38_external_benchmark.py --run_discovered",
            "```",
            "",
        ]
    )


def _write_zip(
    *,
    package_dir: Path,
    out_zip: Path,
    root_name: str,
    include_existing_outputs: bool,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    files = _iter_package_files(package_dir, include_existing_outputs=include_existing_outputs)
    out_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out_zip, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in files:
            relative_path = path.relative_to(package_dir)
            archive_path = Path(root_name) / relative_path
            zf.write(path, archive_path.as_posix())
            rows.append(
                {
                    "archive_path": archive_path.as_posix(),
                    "source_path": str(path),
                    "size_bytes": int(path.stat().st_size),
                    "role": _role_for_path(relative_path),
                }
            )
        readme_path = f"{root_name}/TRANSFER_README.md"
        readme_text = _transfer_readme(root_name)
        zf.writestr(readme_path, readme_text)
        rows.append(
            {
                "archive_path": readme_path,
                "source_path": "generated",
                "size_bytes": len(readme_text.encode("utf-8")),
                "role": "transfer_readme",
            }
        )
    return rows


def _build_report(summary: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# CD38 External Tool Transfer Package",
            "",
            f"- Zip file: `{summary['out_zip']}`",
            f"- Source package: `{summary['package_dir']}`",
            f"- Files packaged: `{summary['file_count']}`",
            f"- Total source bytes: `{summary['total_source_bytes']}`",
            f"- Include existing outputs: `{summary['include_existing_outputs']}`",
            f"- Next-run runbook refresh: `{summary['runbook_refresh']['status']}`",
            "",
            "## Use",
            "",
            "Send the zip to a machine with P2Rank/fpocket or unzip it in WSL/Linux.",
            "The generated preflight workflow resolves package-local paths first, so the transfer zip is not tied to absolute paths from the original project.",
            "Before returning outputs, check `cd38_external_tool_return_checklist.md` so every expected PDB/method output is present.",
            "If `cd38_external_tool_next_run.md` is present, it is the shortest current runbook: it only includes missing benchmark actions, not every reproducibility template.",
            "",
            "Windows:",
            "",
            "```powershell",
            "run_cd38_external_next_benchmark.ps1",
            "```",
            "",
            "Linux / WSL:",
            "",
            "```bash",
            "chmod +x run_cd38_external_next_benchmark.sh",
            "./run_cd38_external_next_benchmark.sh",
            "```",
            "",
            "If you intentionally need every generated template row, use `run_p2rank_templates.*` and `run_fpocket_templates.*` instead.",
            "",
            "After running external tools, copy `p2rank_outputs/` and `fpocket_runs/*/*_out/` back into the original package directory, or use `python import_cd38_external_tool_outputs.py --source <returned_zip_or_dir>`.",
            "",
            "A shorter path is `python finalize_cd38_external_benchmark.py --import_source <returned_zip_or_dir> --run_discovered`, which imports the returned outputs before readiness checks.",
            "If candidate output files are 0, first check the import report `source_diagnosis`, then inspect `cd38_external_tool_output_import_scan.csv` for ignored files and `cd38_external_tool_output_import_coverage.csv` for missing PDB/method pairs.",
            "",
            "If you imported outputs separately, then run `python finalize_cd38_external_benchmark.py --run_discovered`.",
            "",
        ]
    )


def main() -> None:
    args = _build_parser().parse_args()
    package_dir = Path(args.package_dir).expanduser().resolve()
    if not package_dir.exists():
        raise FileNotFoundError(f"Package directory not found: {package_dir}")
    out_dir = Path(args.out_dir).expanduser().resolve()
    root_name = str(args.root_name or package_dir.name).strip() or "external_tool_inputs"
    out_zip = (
        Path(args.out_zip).expanduser().resolve()
        if args.out_zip
        else out_dir / "cd38_external_tool_inputs_transfer.zip"
    )
    runbook_refresh = {"status": "skipped"}
    if not bool(args.skip_runbook_refresh):
        runbook_refresh = _refresh_runbook(package_dir)

    rows = _write_zip(
        package_dir=package_dir,
        out_zip=out_zip,
        root_name=root_name,
        include_existing_outputs=bool(args.include_existing_outputs),
    )
    summary = {
        "package_dir": str(package_dir),
        "out_zip": str(out_zip),
        "out_dir": str(out_dir),
        "root_name": root_name,
        "include_existing_outputs": bool(args.include_existing_outputs),
        "runbook_refresh": runbook_refresh,
        "file_count": int(len(rows)),
        "total_source_bytes": int(sum(int(row["size_bytes"]) for row in rows)),
        "manifest_csv": str(out_dir / "cd38_external_tool_inputs_transfer_manifest.csv"),
        "summary_json": str(out_dir / "cd38_external_tool_inputs_transfer_summary.json"),
        "report_md": str(out_dir / "cd38_external_tool_inputs_transfer_report.md"),
    }
    _write_csv(Path(summary["manifest_csv"]), rows, MANIFEST_COLUMNS)
    Path(summary["summary_json"]).write_text(json.dumps(summary, ensure_ascii=True, indent=2), encoding="utf-8")
    Path(summary["report_md"]).write_text(_build_report(summary), encoding="utf-8")

    print(f"Saved: {out_zip}")
    print(f"Saved: {summary['manifest_csv']}")
    print(f"Saved: {summary['summary_json']}")
    print(f"Saved: {summary['report_md']}")
    print(f"Files packaged: {summary['file_count']}")


if __name__ == "__main__":
    main()
