"""Summarize baseline vs calibrated rule-vs-ML comparison metrics.

Inputs are usually generated by `compare_rule_ml_rankings.py`.
Outputs:
1) calibration_improvement_metrics.csv
2) calibration_improvement_summary.json
3) calibration_improvement_report.md
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


def _safe_float(value: Any) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return float("nan")
    return out if math.isfinite(out) else float("nan")


def _extract_topk_map(summary: dict[str, Any]) -> dict[int, float]:
    out: dict[int, float] = {}
    for item in summary.get("topk_overlap", []) or []:
        try:
            k = int(item.get("k"))
            ratio = _safe_float(item.get("overlap_ratio"))
            if k > 0:
                out[k] = ratio
        except Exception:
            continue
    return out


def _metric_rows(baseline: dict[str, Any], calibrated: dict[str, Any]) -> list[dict[str, Any]]:
    core_metrics = [
        ("score_spearman", "Score Spearman"),
        ("rank_spearman", "Rank Spearman"),
        ("rank_kendall_tau", "Rank Kendall Tau"),
        ("rule_auc", "Rule AUC"),
        ("ml_auc", "ML AUC"),
    ]

    rows: list[dict[str, Any]] = []
    for key, label in core_metrics:
        b = _safe_float(baseline.get(key))
        c = _safe_float(calibrated.get(key))
        delta = c - b if np.isfinite(b) and np.isfinite(c) else float("nan")
        rel = (delta / abs(b)) if np.isfinite(delta) and np.isfinite(b) and abs(b) > 1e-12 else float("nan")
        rows.append(
            {
                "metric_key": key,
                "metric": label,
                "baseline": b,
                "calibrated": c,
                "delta": delta,
                "relative_delta": rel,
            }
        )

    base_topk = _extract_topk_map(baseline)
    cal_topk = _extract_topk_map(calibrated)
    all_k = sorted(set(base_topk.keys()) | set(cal_topk.keys()))
    for k in all_k:
        b = _safe_float(base_topk.get(k))
        c = _safe_float(cal_topk.get(k))
        delta = c - b if np.isfinite(b) and np.isfinite(c) else float("nan")
        rel = (delta / abs(b)) if np.isfinite(delta) and np.isfinite(b) and abs(b) > 1e-12 else float("nan")
        rows.append(
            {
                "metric_key": f"topk_overlap_ratio@{k}",
                "metric": f"Top-{k} Overlap Ratio",
                "baseline": b,
                "calibrated": c,
                "delta": delta,
                "relative_delta": rel,
            }
        )

    return rows


def _build_markdown_report(
    df: pd.DataFrame,
    baseline: dict[str, Any],
    calibrated: dict[str, Any],
    calibrated_config: dict[str, Any] | None,
) -> str:
    lines = [
        "# Calibration Improvement Summary",
        "",
        f"- Common nanobodies: {baseline.get('n_common_nanobodies', 'N/A')}",
        f"- Baseline rule score column: {baseline.get('rule_score_column', 'N/A')}",
        f"- Calibrated rule score column: {calibrated.get('rule_score_column', 'N/A')}",
        "",
        "## Metrics",
        "",
        "| Metric | Baseline | Calibrated | Delta | Relative Delta |",
        "|---|---:|---:|---:|---:|",
    ]
    for _, row in df.iterrows():
        b = row["baseline"]
        c = row["calibrated"]
        d = row["delta"]
        r = row["relative_delta"]
        b_str = f"{b:.6f}" if np.isfinite(b) else "NaN"
        c_str = f"{c:.6f}" if np.isfinite(c) else "NaN"
        d_str = f"{d:+.6f}" if np.isfinite(d) else "NaN"
        r_str = f"{r:+.2%}" if np.isfinite(r) else "NaN"
        lines.append(f"| {row['metric']} | {b_str} | {c_str} | {d_str} | {r_str} |")

    if calibrated_config:
        agg = calibrated_config.get("aggregation_weights", {})
        feat = calibrated_config.get("feature_weights", {})
        top_feat = sorted(
            ((k, _safe_float(v.get("weight"))) for k, v in feat.items()),
            key=lambda x: x[1],
            reverse=True,
        )[:5]

        lines.extend(
            [
                "",
                "## Selected Calibrated Weights",
                "",
                f"- w_mean: {_safe_float(agg.get('w_mean')):.6f}",
                f"- w_best: {_safe_float(agg.get('w_best')):.6f}",
                f"- w_consistency: {_safe_float(agg.get('w_consistency')):.6f}",
                f"- w_std_penalty: {_safe_float(agg.get('w_std_penalty')):.6f}",
                f"- conformer_geo_weight: {_safe_float(agg.get('conformer_geo_weight')):.6f}",
                "",
                "Top-5 feature weights:",
            ]
        )
        for name, weight in top_feat:
            lines.append(f"- {name}: {weight:.6f}")

    return "\n".join(lines) + "\n"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Summarize calibration improvement metrics")
    parser.add_argument("--baseline_summary", required=True, help="Path to baseline ranking_comparison_summary.json")
    parser.add_argument("--calibrated_summary", required=True, help="Path to calibrated ranking_comparison_summary.json")
    parser.add_argument("--calibrated_config", default=None, help="Optional path to calibrated_rule_config.json")
    parser.add_argument("--out_dir", default="improvement_summary", help="Output directory")
    return parser


def main() -> None:
    args = _build_parser().parse_args()

    baseline_path = Path(args.baseline_summary).expanduser()
    calibrated_path = Path(args.calibrated_summary).expanduser()
    if not baseline_path.exists():
        raise FileNotFoundError(f"baseline_summary not found: {baseline_path}")
    if not calibrated_path.exists():
        raise FileNotFoundError(f"calibrated_summary not found: {calibrated_path}")

    baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    calibrated = json.loads(calibrated_path.read_text(encoding="utf-8"))

    config_payload: dict[str, Any] | None = None
    if args.calibrated_config:
        config_path = Path(args.calibrated_config).expanduser()
        if not config_path.exists():
            raise FileNotFoundError(f"calibrated_config not found: {config_path}")
        config_payload = json.loads(config_path.read_text(encoding="utf-8"))

    rows = _metric_rows(baseline=baseline, calibrated=calibrated)
    metrics_df = pd.DataFrame(rows)

    out_dir = Path(args.out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)

    csv_path = out_dir / "calibration_improvement_metrics.csv"
    json_path = out_dir / "calibration_improvement_summary.json"
    md_path = out_dir / "calibration_improvement_report.md"

    metrics_df.to_csv(csv_path, index=False)

    summary_payload = {
        "baseline_summary": str(baseline_path),
        "calibrated_summary": str(calibrated_path),
        "n_metrics": int(metrics_df.shape[0]),
        "metrics": rows,
        "labeling": {
            "baseline": baseline.get("nanobody_labeling"),
            "calibrated": calibrated.get("nanobody_labeling"),
        },
        "calibrated_config": config_payload,
    }
    json_path.write_text(json.dumps(summary_payload, ensure_ascii=True, indent=2), encoding="utf-8")

    report = _build_markdown_report(
        df=metrics_df,
        baseline=baseline,
        calibrated=calibrated,
        calibrated_config=config_payload,
    )
    md_path.write_text(report, encoding="utf-8")

    best_row = metrics_df.loc[metrics_df["metric_key"] == "rule_auc"]
    delta_text = "NaN"
    if not best_row.empty:
        val = _safe_float(best_row.iloc[0]["delta"])
        if np.isfinite(val):
            delta_text = f"{val:+.4f}"

    print(f"Saved: {csv_path}")
    print(f"Saved: {json_path}")
    print(f"Saved: {md_path}")
    print(f"Rule AUC delta (calibrated - baseline): {delta_text}")


if __name__ == "__main__":
    main()
